### ISSUE TITLE
Cleanup?

### ISSUE THREAD

**Issue by mikepurvis** [ros-drivers/nmea_msgs#1]
Consider removing the generated comments from `package.xml` and `CMakeLists.txt`, and releasing a 1.0 version of this.

**Comment by ericperko** [comment]
I don't want to bump the version in Indigo, but this seems reasonable for Jade.

**Comment by mikepurvis** [comment]
@ericperko Do you mind if I release this into Jade?

**Comment by ericperko** [comment]
@mikepurvis Feel free to release. If you want, go ahead and release the driver as well - releasing both has been on my todo list, but I haven't had time to do so (and I don't think that will change until after the DRC Finals in June).
