### ISSUE TITLE
Release for ROS2 Eloquent?

### ISSUE THREAD

**Issue by esteve** [ros-drivers/nmea_msgs#10]
The nmea_msgs package is currently available for ROS2 Crystal and Dashing, but not Eloquent. I'd like to help with that.

**Comment by evenator** [comment]
Thank you! If you make a pull request for the ROS 2 branch that works in Eloquent, (or verify that the current ROS 2 branch builds and works in Eloquent) I'd be happy to release it.

**Comment by esteve** [comment]
@evenator thanks for the quick response. The ros2 branch works flawlessly with Eloquent, I used it to convert a large rosbag from ROSBAG1 to ROSBAG2:

https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/issues/306#note_292118698

**Comment by evenator** [comment]
I've bloomed the package, and it should be in the next eloquent release. https://github.com/ros/rosdistro/pull/23856

**Comment by esteve** [comment]
@evenator thank you so much!
