### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by AndrewLipscomb** [ros-drivers/nmea_msgs#11]
Still early days on the Noetic release, but noticed that this package hasn't been released yet with the major Noetic release today.

Is there any intention to repackage for Noetic and submit for distribution?

**Comment by evenator** [comment]
Hi @ALTinners. Sorry for the tardiness of my response. I'm going to release this package for ROS Noetic today.

**Comment by AndrewLipscomb** [comment]
Party time - excellent
