### ISSUE TITLE
Foxy Release

### ISSUE THREAD

**Issue by JWhitleyWork** [ros-drivers/nmea_msgs#12]
Can the maintainer of this package please release it for Foxy? A Rolling-targeted release would also be appreciated.

**Comment by evenator** [comment]
Hi Josh! Thanks for the reminder. I just bloomed version 2.0.0 for ROS2 Foxy and Rolling:

- Foxy PR is ros/rosdistro#26421
- Rolling PR is ros/rosdistro#26422

**Comment by JWhitleyWork** [comment]
Thanks!
