### ISSUE TITLE
New NMEA Messages?

### ISSUE THREAD

**Issue by evenator** [ros-drivers/nmea_msgs#4]
I currently have a desire for specific ROS messages for each of the NMEA message types (GPGGA, GPGSA, etc), with all of their fields expressed in the native datatype rather than just encapsulating the sentence string in a ROS message.

I had planned to create a new package for the task, but if the maintainers would accept a PR, I think this package would be a good place for those messages. Should I contribute those messages to this package?

**Comment by jack-oquin** [comment]
This package currently has only a generic [Sentence message](http://docs.ros.org/api/nmea_msgs/html/msg/Sentence.html). I don't remember the rationale for that approach.

Do you envision the new messages being used by different subscriber nodes? Would those node only work with particular message types?

**Comment by evenator** [comment]
Right now, I only need them for data logging. The generic Sentence message would still leave me having to parse the message on the post-processing side and makes introspection of a live system with ROS tools like `rqt_plot` impossible.

If other devs want to change any of the navsat drivers to parse the sentences into specific messages, I'll leave that to them--I'm using a proprietary driver that I can't release at this time. On the other hand, I can release the messages, and this seems like the best place for them.

**Comment by evenator** [comment]
Closed by #5
